/*
 * Login.java
 *
 * Created on January 16, 2008, 11:23 AM
 */

package jabbers;
import javax.swing.*;
import java.sql.*;
import java.net.*;
import java.util.Enumeration;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author  hash
 */
public class Login extends JFrame {
    
    /** Creates new form Login */
    String usr;
    char pwd[]=new char[50];
    char pwd1[]=new char[50];
    Pattern p = Pattern.compile("\\b(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\b");
    
    public Login() {
        
        initComponents();
       
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jabbers Messenger");
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\hash\\Desktop\\project_pirates\\icons\\Smiley Face_icon.jpg"));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\hash\\Desktop\\project_pirates\\icons\\jab_chil.JPG"));
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("Jabbers ID");

        jTextField1.setToolTipText("Enter Jabbers ID");
        jTextField1.setName("un");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setText("Password");

        jButton1.setText("Login");
        jButton1.setName("login_button");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPasswordField1.setName("pwd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(jButton1)
                .addContainerGap(202, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        field_validation();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void field_validation()
    {
        if(jTextField1.getText().length()!=0) 
        {
            usr=jTextField1.getText();
            if(jPasswordField1.getPassword().length!=0)
            {
                pwd=jPasswordField1.getPassword();
                login_check();
                
            }
            else
            {
                 JOptionPane.showMessageDialog(null,"Please Enter Password","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Enter UserID","Error",JOptionPane.ERROR_MESSAGE);
            jTextField1.setText("");
            jPasswordField1.setText("");
        }
    }
    public void login_check()
    {
        try
        {
           Class.forName("oracle.jdbc.driver.OracleDriver");
           Connection con=DriverManager.getConnection("jdbc:oracle:thin:@59.93.119.150:1521:XE","hr","hr");
           PreparedStatement pstmt = con.prepareStatement("SELECT user_name FROM user_details WHERE user_name = ?");
            pstmt.setString(1,usr);
            ResultSet rs = pstmt.executeQuery();
            if(rs.next())
            {
              if(rs.getString("user_name").equals(usr))
              {   
             
               pstmt = con.prepareStatement("select password from user_details where user_name = ?");
               pstmt.setString(1,usr);
               rs = pstmt.executeQuery();
               if(rs.next())
                {
                 pwd1=rs.getString("password").toCharArray();
                 int flg=0;
                 for(int i=0;i<pwd1.length;i++)
                 {
                   if((pwd1[i]!=pwd[i])||(pwd1.length!=pwd.length))   
                   {  flg=1;   }
                 }
                 if(flg==0)
                 {set_ip();con.close();pstmt.close();rs.close();}
                 else
                 {
                    JOptionPane.showMessageDialog(null,"Invalid Password","Error",JOptionPane.ERROR_MESSAGE);
                    jTextField1.setText("");
                    jPasswordField1.setText("");
                 }
                     
               }
               else
               {
                   JOptionPane.showMessageDialog(null,"Invalid Password","Error",JOptionPane.ERROR_MESSAGE);
                    jTextField1.setText("");
                    jPasswordField1.setText("");
               }
              }
            }
            else
            {
               JOptionPane.showMessageDialog(null,"Invalid UserID","Error",JOptionPane.ERROR_MESSAGE);
               jTextField1.setText("");
               jPasswordField1.setText("");
            }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null,"Error Connecting","Error",JOptionPane.ERROR_MESSAGE);
            
        }
    }
    
    public void set_ip()
    {
        try
        {
            Enumeration e = NetworkInterface.getNetworkInterfaces();
            String ip[]=new String[50];
            String ip_address;
            int v=0;
            while (e.hasMoreElements()) {
            NetworkInterface i = (NetworkInterface) e.nextElement();
            ip_address=i.toString(); 
            Matcher m=p.matcher(ip_address);
            if(m.find())
            {
			ip[v]=ip_address.substring(m.start(),m.end());
                        v++;
	    }
            }
           ip_address=ip[v-1];
           Class.forName("oracle.jdbc.driver.OracleDriver");
           Connection con=DriverManager.getConnection("jdbc:oracle:thin:@59.93.119.150:1521:XE","hr","hr");
           PreparedStatement ps=con.prepareStatement("update user_details set ip_address = ? where user_name = ? ");
           ps.setString(1,ip_address);
           ps.setString(2,usr);
           int rows=ps.executeUpdate();
           if(rows==1)
           {
              
               Login_groups lg=new Login_groups(usr);
               con.close();
               ps.close();
               lg.setVisible(true);
               this.setVisible(false);
               this.dispose();
               
           }
           else
           {
               JOptionPane.showMessageDialog(null,"Error Connecting","Error",JOptionPane.ERROR_MESSAGE);
               jTextField1.setText("");
               jPasswordField1.setText("");
           }
        }
        catch(Exception ex)
        { JOptionPane.showMessageDialog(null,ex.toString());
          System.exit(0);
        }
     
       
         
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    
}
