/*
 * Login_groups.java
 *
 * Created on January 19, 2008, 11:37 PM
 */

package jabbers;

import java.sql.*;
import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
/**
 *
 * @author  hash
 */
public class Login_groups extends javax.swing.JFrame {
    String usr;
    String groups[]=new String[100];
    JCheckBox jcb[]=new JCheckBox[100];
    String group[]=new String[100];
    int j,k=0;
    
    /** Creates new form Login_groups */
    public Login_groups(String usr) {
        this.usr=usr;
        initComponents();
        this.setSize(276,792);
        jLabel1.setText(usr+"'s groups");
        get_groups();
    }
    
    public void get_groups()
    {
        
        try
        {
        Class.forName("oracle.jdbc.driver.OracleDriver");
        Connection con=DriverManager.getConnection("jdbc:oracle:thin:@59.93.119.150:1521:XE","hr","hr");
        PreparedStatement pstmt=con.prepareStatement("select group_name from user_rtr where user_name = ?");
        pstmt.setString(1,usr);
        ResultSet rs=pstmt.executeQuery();
        int i=0;
        while(rs.next())
        {
            groups[i]=rs.getString(1);
            i++;
        }
        int width=100,height=20;
        int y=30;
        for(j=0;j<groups.length&&groups[j]!=null;j++)
        {
            jcb[j]=new JCheckBox(groups[j],false);
            jcb[j].setVisible(true);
            jcb[j].setBounds(30,y,width,height);
            jList1.add(jcb[j]);
            y+=30;
            
                 
        }
            
        jList1.setVisible(true);
        
                        
        }
        catch(Exception ex)
        {  ex.printStackTrace(); }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jabbers Messenger");
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jList1.setBackground(new java.awt.Color(238, 238, 238));
        jList1.setEnabled(false);
        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jButton1)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        
      for(int i=0;i<j;i++)  
      {
          if(jcb[i].isSelected())
          {
              group[k]=jcb[i].getText();
               k++;
          }
      }
        new Group_users(usr,group,k);
        this.setVisible(false);
        this.dispose();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_groups("a").setVisible(true);
            }
        });
    }*/
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
