/*  Program to find whether a given string is generated by 1*001*0 Regular Expression
 *
 *    .<---1----.                .<---1----.  
 *    |         |  0           0 |         |  0
 * ---->state1------->state2------>state3------->end 
 *
 * Observe the above state diagram to understand the logic the following program.........
 */
#include<stdio.h>
#include<string.h>
#include<conio.h>
main()
{
	//flag == 1 indicates error....
	int flag=0,i=0;
	char c[100];
	clrscr();
	printf("\nEnter the string :");
	scanf("%s",c);
state1:	
	do{
		if(c[i] == '1') continue;
		else if(c[i] == '0') goto state2;
		else {flag = 1; goto End;}
	}while(c[i++] != '\0');
	{flag = 1; goto End;}
state2:
	i++;
	if(c[i] == '0') goto state3;
	else {flag = 1; goto End;}
state3:
	do{
		i++;
		if(c[i] == '1') continue;
		else if(c[i] == '0'&&c[i+1]=='\0') goto End;
		else {flag = 1; goto End;}
	}while(c[i] != '\0');
	{flag = 1; goto End;}
End:
	printf("\n%s is %s a Valid Pattern",c,flag==0?"":"Not"); 
	getch();
}
/*
INPUT:
	Enter the string : 10010
OUTPUT:   
	10010 is a Valid Pattern
*/	
