/*
 * Group_users.java
 *
 * Created on January 23, 2008, 3:31 PM
 */

package jabbers;
import javax.swing.*;
import javax.swing.tree.*;
import java.sql.*;
import java.io.*;
import java.net.*;

/**
 *
 * @author  hash
 */
public class Group_users extends javax.swing.JFrame implements Runnable{
    String a[];
    int k,l=0;
    String usr;
    DefaultMutableTreeNode dmtn[];
    DefaultMutableTreeNode top;
    String user_name[]=new String[1000];
    String group_name[]=new String[1000];
    DefaultMutableTreeNode ntmd[]=new DefaultMutableTreeNode[1000];
    Connection con;
    
    
    /** Creates new form Group_users */
    public Group_users(String usr,String a[],int k) {
        this.usr=usr;
        this.a=a;
        this.k=k;
        System.out.println("Entered");
        initComponents();
        this.setSize(276,792);
        this.setVisible(true);
        top=new DefaultMutableTreeNode("<html><h3>Groups</html>");
        dmtn=new DefaultMutableTreeNode[k];
        jMenuBar1.add(new JMenu("Actions"));
        jMenuBar1.add(new JMenu("Help"));
        set_nodes();
        get_users();
        DefaultTreeModel dtm=new DefaultTreeModel(top);
        /*renderer = (DefaultTreeCellRenderer)jTree1.getCellRenderer();
        renderer.setOpenIcon(new ImageIcon("C:\\Documents and Settings\\hash\\Desktop\\project_pirates\\icons\\offline.gif"));*/
        jTree1.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        jTree1.setModel(dtm);
        try {
            
            Class.forName("oracle.jdbc.driver.OracleDriver");
            con=DriverManager.getConnection("jdbc:oracle:thin:@59.93.119.150:1521:XE","hr","hr");
        } catch (Exception ex) {
            ex.printStackTrace();
            
        }
        jTree1.setVisible(true);
        Thread th=new Thread(this);
        th.start();
        
        
        
    }
    public void set_nodes() {
        
        for(int i=0;i<k;i++) {
            dmtn[i]=new DefaultMutableTreeNode("<html><h4>"+a[i]+"</html>");
            top.add(dmtn[i]);
        }
        
    }
    
    public void get_users(){
        try {
            
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@59.93.119.150:1521:XE","hr","hr");
            for(int i=0;i<k;i++) {
                PreparedStatement pstmt=con.prepareStatement("select user_name,status from user_rtr where group_name = ?");
                pstmt.setString(1,a[i]);
                ResultSet rs=pstmt.executeQuery();
                while(rs.next()) {
                    if(rs.getString(2).equalsIgnoreCase("online")) {
                        group_name[l]=new String(a[i]);
                        user_name[l]=new String(rs.getString(1));
                        ntmd[l]=new DefaultMutableTreeNode("<html><b>"+user_name[l]+"</html>");
                        
                    } else {
                        group_name[l]=new String(a[i]);
                        user_name[l]=new String(rs.getString(1));
                        ntmd[l]=new DefaultMutableTreeNode(user_name[l]);
                    }
                    dmtn[i].add(ntmd[l]);
                    l++;
                    
                }
            }
            
            
            
        } catch(Exception ex) {
        }
    }
    public void start_msg(String grp,String usr,String st){
        try {
            
            PreparedStatement pstmt=con.prepareStatement("select ip_address from user_details where user_name = ?");
            pstmt.setString(1,usr);
            ResultSet rs=pstmt.executeQuery();
            if(rs.next())
            {   String ip=rs.getString(1);
                new Client_run(grp,usr,ip);
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
        }
                
       // System.out.println(grp+usr+st);
    }
    
    public void run() {
        try {
            
            ServerSocket ss=new ServerSocket(22244);
            while(true) {
            new Host_run(usr,ss.accept());
            }
            
        } catch (IOException ex) {
            ex.printStackTrace(); }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jabbers Messenger");
        setBounds(new java.awt.Rectangle(0, 0, 276, 792));
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(jTree1);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\hash\\Desktop\\project_pirates\\icons\\jab_chil.JPG"));

        jMenu1.setText("Messenger");
        jMenu1.setBorderPainted(true);
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
// TODO add your handling code here:
        
        int i;
        for(i=0;i<l;i++) {
            if(jTree1.getLastSelectedPathComponent().toString().equals(ntmd[i].getUserObject().toString())) {
                try {
                    
                    PreparedStatement pstmt=con.prepareStatement("select status from user_rtr where group_name = ? and user_name = ?");
                    pstmt.setString(1,group_name[i]);
                    pstmt.setString(2,user_name[i]);
                    ResultSet rs=pstmt.executeQuery();
                    
                    if(rs.next()) {
                        String stat=new String(rs.getString(1));
                        if(true) {
                        start_msg(group_name[i],user_name[i],stat);}
                    }
                    
                } catch (SQLException ex) { ex.printStackTrace(); }
                
                break;
            }
            
        }
        
        
    }//GEN-LAST:event_jTree1ValueChanged
    
    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String a[]={"x","y","z"};
                new Group_users("a",a,3).setVisible(true);
            }
        });
    }*/
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
    
}
