[package]
name = "practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
time = "0.3"
unicode-width = "0.2.0"
bitflags = "2.6.0"
bitfield-struct = "0.9.2"
