/* Support.h */
/* Definitions of all symbolic constants and common
   utility functions used throughout the example programs. */

/* IT IS BEST TO DEFINE UTILITY_EXPORTS AND _STATICLIB WITHIN THE
   PROJECT RATHER THAN HERE, BUT THE DESCRIPTIONS ARE INCLUDED. */
/* The name "UTILITY_EXPORTS" is generated by Dev Studio when you
   create a DLL project named "Utility" and it is defined on the
   C command line. */

//  UTILITY_3_0_EXPORTS is defined within the UTILITY_3_0 project.

#if defined(UTILITY_3_0_EXPORTS)
#define LIBSPEC _declspec (dllexport)
#elif defined(__cplusplus)
#define LIBSPEC extern "C" _declspec (dllimport)
#else
#define LIBSPEC _declspec (dllimport)
#endif

#define EMPTY _T ("")
#define YES _T ("y")
#define NO _T ("n")
#define CR 0x0D
#define LF 0x0A
#define TSIZE sizeof (TCHAR)

/* Limits and constants. */
#define TYPE_FILE 1          /* Used in ls, rm, and lsFP. */
#define TYPE_DIR 2
#define TYPE_DOT 3

#define MAX_OPTIONS 20        /* Max # of command line options. */
#define MAX_ARG 1000          /* Max # of command line arguments. */
#define MAX_COMMAND_LINE MAX_PATH+50   /* Max size of a command line. */
/* Commonly used functions. */
LIBSPEC BOOL ConsolePrompt (LPCTSTR, LPTSTR, DWORD, BOOL);
LIBSPEC BOOL PrintStrings (HANDLE, ...);
LIBSPEC BOOL PrintMsg (HANDLE, LPCTSTR);
LIBSPEC VOID ReportError (LPCTSTR, DWORD, BOOL);
LIBSPEC VOID ReportException (LPCTSTR, DWORD);
LIBSPEC DWORD Options (int, LPCTSTR *, LPCTSTR, ...);
LIBSPEC LPTSTR SkipArg (LPCTSTR);
LIBSPEC VOID GetArgs (LPCTSTR, int *, LPTSTR *);

/* Collection of generic string functions modeled after string.h.
   Created as required -- there was only one! Implementation is
   derived from Plauger: The Standard C Library. */

LIBSPEC LPCTSTR wmemchr (LPCTSTR, TCHAR, DWORD);

#ifdef _UNICODE /* This declaration had to be added. */
#define _tstrrchr wcsrchr
#else
#define _tstrrchr strrchr
#endif

#ifdef _UNICODE /* This declaration had to be added. */
#define _memtchr wmemchr
#else
#define _memtchr memchr
#endif

/* Security functions. */
LPSECURITY_ATTRIBUTES InitializeUnixSA (DWORD, LPTSTR, LPTSTR,
   LPDWORD, LPHANDLE);
LPSECURITY_ATTRIBUTES InitializeAccessOnlySA (DWORD, LPTSTR, LPTSTR,
   LPDWORD, LPHANDLE);
DWORD ReadFilePermissions (LPTSTR, LPTSTR, LPTSTR);
BOOL ChangeFilePermissions (DWORD, LPTSTR, LPDWORD, LPDWORD);
/* Simpler forms available with Visual C++ Version 5.0. */
//PSECURITY_DESCRIPTOR InitializeSD (DWORD, LPTSTR, LPTSTR, LPDWORD);

/* Constants needed by the security functions. */
#define LUSIZE 1024
#define ACCT_NAME_SIZE LUSIZE


