set nocompatible
execute pathogen#infect()
set ttyfast
set nu
syntax on
filetype plugin indent on
set cindent
set shiftwidth=4
set tabstop=4
"set noexpandtab
set incsearch
set ignorecase
set hlsearch
set ruler

"set textwidth=78
"set wrapmargin=80
set lazyredraw

"no sounds
set noerrorbells
set novisualbell

"set lines=999 columns=999

syn keyword cType uint ubyte ulong uint64_t uint32_t uint16_t uint8_t boolean_t int64_t int32_t int16_t int8_t u_int64_t u_int32_t u_int16_t u_int8_t u8 wait_queue_head_t atomic_t
set showmode
"set gdefault  					"search/replace "globally" (on a line) by default
set laststatus=2                " tell VIM to always put a status line in, even
                                "    if there is only one window
set wildmenu                    " make tab completion for files/buffers act like bash
set wildmode=list:full          " show a list when pressing tab and complete
                                "    first full match
set showcmd                     " show (partial) command in the last line of the screen
                                "    this also shows visual selection info
colorscheme Tomorrow-Night-Bright  
set pastetoggle=<F2>
set listchars=tab:\|\ ,eol:$,trail:-
set backspace=indent,eol,start
set wrap
set wildmode=longest:full,full
set colorcolumn=100

"change current directory
autocmd BufEnter * silent! lcd %:p:h

"set cursorline
"hi CursorLine   cterm=NONE ctermbg=59
"hi CursorLine   cterm=NONE ctermbg=darkred "ctermfg=white guibg=darkred guifg=white
":autocmd InsertEnter * set cul "Cursor line will be set only in insertmode
":autocmd InsertLeave * set nocul "No cursor line in other modes

set showmatch
hi MatchParen cterm=underline ctermfg=blue ctermbg=none "Highlight only other matching brace(not both) in red

"set clipboard=unnamedplus
"Enabling spell check for all
"set spell

au BufNewFile,BufRead COMMIT_EDITMSG set spell
hi clear SpellBad
hi SpellBad cterm=underline
hi clear SpellCap
hi SpellCap cterm=underline
hi clear SpellRare
hi SpellRare cterm=underline
hi clear SpellLocal
hi SpellLocal cterm=underline

"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif

"Correct common mistakes
:command WQ wq
:command Wq wq
:command W w
:command Q q

"Calculator
:command! -nargs=+ Calc :py print <args>
":py from math import *

"Date time
:nnoremap <F5> "=strftime("%c")<CR>P
:inoremap <F5> <C-R>=strftime("%c")<CR>

"C, C++ compilers
au FileType c setlocal makeprg=clang\ -Wall\ \"%\"
au FileType cpp setlocal makeprg=clang++\ -Wall\ -std=c++11\ \"%\"\ -o\ a.exe

"source $VIMRUNTIME/vimrc_example.vim
"source $VIMRUNTIME/mswin.vim
"behave mswin

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let eq = ''
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      let cmd = '""' . $VIMRUNTIME . '\diff"'
      let eq = '"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
endfunction
"No swapfiles
set nobackup
set noswapfile
set nowritebackup

